### ISSUE TITLE
@conda-forge-admin, please add user @jan-janssen

### ISSUE THREAD

**Issue by jan-janssen** [conda-forge/python-keycloak-feedstock#63]
### Additional comment:

@conda-forge-admin, please add user @jan-janssen

**Comment by fcollonval** [comment]
@jan-janssen for posterity would you mind writing your reason to maintain this recipe?

**Comment by jan-janssen** [comment]
Hi @fcollonval , I currently maintain close to [600 conda-forge packages](https://github.com/jan-janssen/conda-forge-contribution) primarily from the field of materials science. In the specific case of `python-keycloak` it is a dependency of [`nomad-lab`](https://github.com/conda-forge/nomad-lab-feedstock). So by joining you in maintaining `python-keycloak` I can make sure it stays compatible to [`nomad-lab`](https://github.com/conda-forge/nomad-lab-feedstock).
